version: '3'
services:
  glados-llm:
    build: .
    image: makespacemadrid/glados-mqtt-llm:latest
    hostname: mqtt-llm
    env_file:
      - .env
    volumes:
      - ./data:/data
    restart: alwaysm