version: '3'


services:
  mqtt-slack:
    build: .
    image: makespacemadrid/glados-mqtt-slack:latest
    env_file:
      - .env
    environment:
      - MQTT_PORT = 1883
      - MQTT_HOST = glados.makespacemadrid.org
      - SLACK_API_TOKEN = ${SLACK_API_TOKEN}
      - SLACK_PORT = 5000 # No estoy seguro que funcione 
    restart: always
    ports:
      - 5000:5000