version: '3'


services:
  glados-slack:
    build: .
    image: makespacemadrid/glados-mqtt-slack:latest
    hostname: mqtt-slack
    env_file:
      - .env
    environment:
      - SLACK_PORT = 5000 # No estoy seguro que funcione 
    restart: always
    ports:
      - 5000:5000