version: '3'
services:
  glados-nvidia:
    build: .
    image: makespacemadrid/glados-nvidia:latest
    hostname: mqtt-nvidia
    env_file:
      - .env
#    volumes:
#      - ./data:/data
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]