version: '3'
services:
  glados-spaceapi:
    build: .
    image: makespacemadrid/glados-mqtt-spaceapi:latest
    hostname: mqtt-spaceapi
    volumes:
      - ./spaceapi:/spaceapi
    environment:
      - MQTT_PORT=1883
      - MQTT_HOST=mqtt.makespacemadrid.org
    restart: always

  nginx-spaceapi:
    image: nginx:latest
    ports:
      - 8800:80
    volumes:
      - ./spaceapi:/usr/share/nginx/html
    restart: always