version: '3'


services:
  mqtt-slack:
    build: .
    image: makespacemadrid/glados-mqtt-telegram:latest
    hostname: mqtt-telegram
    env_file:
      - .env
    restart: always
    ports:
      - 5000:5000