version: '3'
services:
  glados_node:
    build: .
    image: makespacemadrid/glados-base-node:1.0
    hostname: base-node
#    ports:
#      - "8080:8080" # Cambia el puerto si es necesario
    environment:
      - MQTT_PORT=1883
      - MQTT_HOST=mqtt.makespacemadrid.org